version: "3.8"
services:
  tauthoro:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BASEIMGTAG=${BASEIMGTAG}
    command: ./tauthoro
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file: .env.tauthoro
    environment:
      DB_HOST: db
      DB_PORT: "5432"
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:delegated
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env.db

volumes:
  db-data:
